[list_types]
bytes = 235
cost = 7122
input = "()"
output = "10"
hash = "ab24ceb9925eb136dc0d19cedbdf0c5f1fca4fa20dc9fffa47f6159603f098c6"

[pair_types]
bytes = 81
cost = 3298
input = "()"
output = "88"
hash = "a838ad16af65415481785017fd17260052edf77f40a14bafbbc0ea012c4f199c"

[struct_type]
bytes = 161
cost = 3019
input = "()"
output = "\"Older\""
hash = "0805d86735757b42ff0ad4194d8f356d6a600e8a2cd6494ecb50a8d586ffe1ef"

[nested_scopes]
bytes = 421
cost = 20043
input = "(42)"
output = "0x01250d618f00"
hash = "f62477bea5e9e0499265972002bf8205e064467c75a652d95302d0aacbbc6f25"

[lambda_functions]
bytes = 103
cost = 3247
input = "()"
output = "86"
hash = "4487281127571db9621d134467f47ec74af9becea41a45fb942610b5df172328"

[hello_world]
bytes = 24
cost = 175
input = "()"
output = "\"Hello, world!\""
hash = "7cacd67079cbf0a1cd915e9456ebb09fca6d375a63744e4e0e442b8f00759d24"

[lists]
bytes = 219
cost = 6266
input = "()"
output = "21"
hash = "0f8516625bd122a47b5ad2bb871034ff13dd175cca88c4a0641f8a4d7ee95d7d"

[fibonacci]
bytes = 121
cost = 414329
input = "()"
output = "55"
hash = "951ba85ff214a65c4d07814672544b6686e8f4a819550543473fb8eb26aae6a3"

[let_bindings]
bytes = 81
cost = 5063
input = "(5 10)"
output = "9"
hash = "aa247d144d1c5a3554c3d689c09fb2c0aced58a628e52030eac2bbd219018289"

[constants]
bytes = 47
cost = 2347
input = "()"
output = "350"
hash = "25f386f3f2852cc89a4e21002fd1c6dcf7e0000b069f18d4c80d42224e15fd41"

[closures]
bytes = 207
cost = 40815
input = "(10)"
output = "0x375f00"
hash = "95e0d0d8c8853d0cca7172f9c9cbe75b32d90055935431132b7adf66eb3e6cc2"

[factorial]
bytes = 97
cost = 43743
input = "()"
output = "0x013077775800"
hash = "291e4594b43d58e833cab95e4b165c5fac6b4d8391c81ebfd20efdd8d58b92d8"

[enums]
bytes = 135
cost = 1327
input = "()"
output = "((g1_multiply \"Hello, world!\" \"Message thingy\") (g1_negate \"Some puzzle\" 100))"
hash = "e49ff16e836bdc3860d919f4d9dd8e562e544f569230229ba86409cab2d3e5e2"

[signature_puzzle]
bytes = 221
cost = 29486
input = "(0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8554bf5122f344554c53bde2ebb8cd2b7e3 ((51 0xdbc1b4c900ffe48d575b5da5c638040125f65db0fe3e24494b76ea986457d986 1000)))"
output = "((g1_multiply 0xe3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b8554bf5122f344554c53bde2ebb8cd2b7e3 0x7fb7b7ef9333621162729d06e60efbb19eed37c736b2b467db2f9571586c3b6a) (g1_negate 0xdbc1b4c900ffe48d575b5da5c638040125f65db0fe3e24494b76ea986457d986 1000))"
hash = "6e94aaf18c8348b6e01f4c01973a415a691be93f51e81666ed34760a9ee953bb"

[many_lets]
bytes = 251
cost = 14490
input = "()"
output = "7260"
hash = "dc340fbeed3c3753160d9683c4c97a5b3297c1169e83eb1ff8e1544163528b8d"

[complex_spreads]
bytes = 169
cost = 19078
input = "()"
output = "550"
hash = "af78d09d3fa66ec50827f2dd1877bc249a526bf96d42f72686e3120826b6a883"

[type_guards]
bytes = 160
cost = 7060
input = "()"
output = "6"
hash = "c65b731dc627a8ad1357dee68e27e3de33a582bebdb0bc2b503310e20ad360cc"

[early_return]
bytes = 115
cost = 2716
input = "(50)"
output = "\"Small\""
hash = "cf32bd32ff878903a6962acd218c451474e0ef3ae3c649f79aa5abca1bff730b"
